// The photo and video library, generated by `npm run media` into media.json.
import data from './media.json';

export const photos = data.photos;
export const videos = data.videos;
export const childhood = data.childhood || [];
export const portraits = photos.filter((p) => p.portrait);
export const landscapes = photos.filter((p) => !p.portrait);

export function byId(id) {
  return photos.find((p) => p.id === id) || videos.find((v) => v.id === id) || childhood.find((p) => p.id === id) || null;
}

// A content entry can name a photo by id ("p07") or give a path. Both resolve to a URL.
export function photoSrc(ref, { thumb = false } = {}) {
  const item = byId(ref);
  if (item) return thumb && item.thumb ? item.thumb : item.src;
  return ref;
}

export function shuffled(list, seed = Date.now()) {
  const out = [...list];
  let s = seed % 2147483647;
  const rnd = () => (s = (s * 48271) % 2147483647) / 2147483647;
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// Photos with a video slipped in after every `every` photos.
export function interleaved(every = 3) {
  const out = [];
  let v = 0;
  photos.forEach((p, i) => {
    out.push(p);
    if ((i + 1) % every === 0 && v < videos.length) out.push(videos[v++]);
  });
  while (v < videos.length) out.push(videos[v++]);
  return out;
}
